### ISSUE TITLE
Suggestion/Question: deferred-all

### ISSUE THREAD

**Issue by aguerrieri** [gptankit/serviceq#5]
I have a use case where I would like to defer ALL requests, no matter the outcome. What I need is to respond to the original request as fast as possible with some pre-defined response, and then let ServiceQ handle a slower back-end. Obviously, the original request would always succeed and there would be no direct way to tell if the deferred request succeeded or not. I checked the documentation and learned about the deferred queue, but from what I understand it would only kick-in when a request fail, and not for all cases. Is this something that could be implemented easily? Would it be useful to others?

**Comment by gptankit** [comment]
This is certainly useful for applications that require a short lived queue for processing events. It requires some code change - basically skip _dialAndSend()_ and set _toBuffer_ flag based on a user config.

**Comment by gptankit** [comment]
This is live now as part of this PR: https://github.com/gptankit/serviceq/pull/9. Added an ENABLE_UPFRONT_Q setting to allow selected requests to be processed asynchronously. The request formats can be configured as part of Q_REQUEST_FORMATS setting.
