### ISSUE TITLE
Getting 503 Request Buffered

### ISSUE THREAD

**Issue by jungalwala** [gptankit/serviceq#7]
With the sq.properties listed below, if I query once I get results.  But if I put any kind of concurrent load through the serviceq I immediately get a 503 (Request Buffered).  Not sure what I am doing wong.

`#ServiceQ Configuration File

#------------------#
# Cluster Settings #
#------------------#

#Port on which serviceq listens on
LISTENER_PORT=5252

#Protocol the endpoints listens on -- 'http' for both http/https
PROTO=http

#Endpoints seperated by comma (,) -- no spaces allowed, can be a combination of http/https
ENDPOINTS=https://c1.xxx.com,https://c2.xxx.com,https://c3.xxx.com

#Concurrency peak defines how many max concurrent connections are allowed to the cluster of endpoints defined above
CONCURRENCY_PEAK=8096

#Timeout (ms) is added to each outgoing request to endpoints, the existing timeouts are overriden, value of -1 means no timeout
OUTGOING_REQUEST_TIMEOUT=300000

#Interval (ms) between two retries -- recommended 0 for best performance
RETRY_GAP=0

#-------------------------#
# Deferred Queue Settings #
#-------------------------#

#Enable deferred queue for requests on final failures (cluster down)
ENABLE_DEFERRED_Q=true

#Request format enables deferred queue on only the mentioned method and route -- picked up if ENABLE_DEFERRED_Q is true
#DEFERRED_Q_REQUEST_FORMATS=POST /orders,PUT,PATCH,DELETE
DEFERRED_Q_REQUEST_FORMATS=ALL
#DEFERRED_Q_REQUEST_FORMATS=POST,PUT,PATCH,DELETE

#-------------------#
# Response Settings #
#-------------------#

#Custom response headers to be forwarded to client -- no spaces allowed
#CUSTOM_RESPONSE_HEADERS=Connection: keep-alive|Server
CUSTOM_RESPONSE_HEADERS=Server

#Keep Alive Timeout (ms), value of -1 means no timeout
KEEP_ALIVE_TIMEOUT=120000

#--------------#
# SSL Settings #
#--------------#

#Use SSL connection
SSL_ENABLE=false

#Path to certificate and private keys (do not provide quotes "") -- picked up if SSL_ENABLE is true
SSL_CERTIFICATE_FILE=/usr/certs/cert.pem
SSL_PRIVATE_KEY_FILE=/usr/certs/key.pem
`

**Comment by jungalwala** [comment]
I found my own issue.  My ulimit -n on my machine was set lower than the number of CONCURRENCY_PEAK

**Comment by gptankit** [comment]
Have kept this issue under https://github.com/gptankit/serviceq/wiki/Common-Pitfalls
